# Generated by Django 3.2.7 on 2021-09-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brain_MRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MRI_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
