# Generated by Django 3.2.7 on 2021-09-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brain_mri',
            name='MRI_image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
