# Generated by Django 3.2.7 on 2021-09-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_alter_brain_mri_mri_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brain_mri',
            name='MRI_image',
            field=models.ImageField(upload_to='./media/images/'),
        ),
    ]
